antfu/node-modules-inspector

packages/node-modules-tools/test/list.test.ts, vitest.config.ts
updates snapshot creation to prevent flaky tests: https://github.com/antfu/node-modules-inspector/pull/6#issuecomment-2631532216
=> test: update snapshot creation

packages/node-modules-inspector/src/app/components/graph/Canvas.vue
This sets the cursor to grabbing when moving the canvas
=> feat(graph): grab cursor

packages/node-modules-inspector/src/app/components/report/MostDeps.vue
=> feat: load more transitive dependencies

.github/workflows/release-commit.yml
Install app first: https://github.com/apps/pkg-pr-new
=> ci: publish on any commit

packages/node-modules-inspector/src/app/state/payload.ts
negative filter when starts with `!`
=> feat: negative filter

packages/node-modules-inspector/src/app/utils/file-category.ts, packages/node-modules-tools/src/size.ts, packages/node-modules-tools/src/types/size.ts
=> feat: display more formats

packages/node-modules-inspector/src/app/components/report/ExpendableContainer.vue
https://github.com/user-attachments/assets/887a886a-f8d2-4884-92c1-7bf7ea13ec59
https://github.com/user-attachments/assets/796cbfe5-7c25-46be-819c-90e1ad2ab212
=> fix(ExpandableContrainer): adjust more button position when overflow

packages/node-modules-inspector/src/app/components/panel/PackageDetails.vue, packages/node-modules-tools/src/resolve.ts, packages/node-modules-tools/src/types/node.ts, packages/node-modules-tools/test/list.test.ts
This PR add package funding info.
=> feat: add package funding info

packages/node-modules-inspector/src/app/components/display/NumberBadge.vue, packages/node-modules-inspector/src/app/components/report/ExpendableContainer.vue
=> feat: enhance expandable container with "More" and "All" buttons

packages/node-modules-inspector/build.config.ts, packages/node-modules-inspector/src/node/config.ts
- fix the `alias` of `src` in `build.config.ts`
- export `NodeModulesInspectorConfig`
=> fix: fix and export the config type

packages/node-modules-inspector/src/app/components/panel/Dark.vue, packages/node-modules-inspector/src/app/components/panel/Nav.vue
=> fix: button title

packages/node-modules-inspector/src/app/components/panel/PackageDetails.vue
This PR adds support for resolving repository url by repository slug.
None.
None.
=> feat: resolve repository url from repository slug

packages/node-modules-inspector/src/app/backends/dev.ts
Modify from absolute path to relative path for --base parameter compatibility
=> feat: metadata api support custom base

packages/node-modules-inspector/src/app/components/report/Licenses.vue
reference: #73 
This PR adds `0BSD` to permissive licenses.
=> feat: add `0BSD` to permissive licenses

packages/node-modules-inspector/src/app/components/report/Funding.vue
this PR fixes some grammatical issues/typos in the funding component.
N/A
=> fix: typos in funding component

packages/node-modules-inspector/src/app/components/report/Deprecated.vue, packages/node-modules-inspector/src/app/components/report/Engines.vue, packages/node-modules-inspector/src/app/components/report/Funding.vue, packages/node-modules-inspector/src/app/components/report/InstallSize.vue, packages/node-modules-inspector/src/app/components/report/Licenses.vue, packages/node-modules-inspector/src/app/components/report/MultipleVersions.vue, packages/node-modules-inspector/src/app/components/report/PublishTime.vue, packages/node-modules-inspector/src/app/components/report/TransitiveDeps.vue, packages/node-modules-inspector/src/app/components/report/UsedBy.vue, packages/node-modules-inspector/src/app/components/ui/EmptyState.vue
This PR implements a new generic `UiEmptyState` component for unified empty state display across report views. By applying the DRY (Don't Repeat Yourself) principle, the previously repeated empty state code in multiple report components has been abstracted into a reusable component, improving code maintainability and consistency.
Main improvements:
1. Added a new `UiEmptyState` component that accepts `title` and `message` properties to standardize empty state styling
2. Refactored the following report components to use the new component instead of duplicated code:
- MultipleVersions
- UsedBy
- InstallSize
- TransitiveDeps
- PublishTime
- Engines
- Funding
- Licenses
- Deprecated
This improvement makes the code more modular and makes adding new report components easier, while ensuring …
=> feat: implement UiEmptyState component for improved empty state handling across reports

packages/node-modules-inspector/src/app/components/panel/FiltersMini.vue, packages/node-modules-inspector/src/app/components/panel/Nav.vue
=> chore: optimize style

packages/node-modules-inspector/src/app/webcontainer/container.ts
This PR increases the timeout period from 5 to 10 seconds. Timeouts should now return an error to indicate that they have timed out.
fixes #98
=> fix: optimize timeout error

packages/node-modules-inspector/src/app/components/panel/Overview.vue, packages/node-modules-inspector/src/app/components/panel/PackageDetails.vue, packages/node-modules-inspector/src/app/components/panel/PackageFunding.vue, packages/node-modules-inspector/src/app/pages/grid/[...grid].vue, packages/node-modules-inspector/src/app/pages/report/[...report].vue
This PR ensures to keep the hash for every nuxt link
=> fix: ensure to always keep hash

packages/node-modules-inspector/src/app/components/display/DeprecationMessage.vue
Fix deprecation link for current version
https://github.com/antfu/node-modules-inspector/issues/112
=> fix: components: display: fix deprecation link for current version

packages/node-modules-inspector/src/app/components/panel/PackageDetails.vue, packages/node-modules-inspector/src/app/pages/grid/[...grid].vue, packages/node-modules-inspector/src/shared/version-info.ts, packages/node-modules-tools/src/types/node.ts, pnpm-lock.yaml, pnpm-workspace.yaml
~~Wait release for fast-npm-meta~~
=> feat: show provenance
